#!/bin/sh
#
# Programs to run on login
#

setxkbmap -layout us &
remap_keys           &	# Switch caps/esc
set_background       &	# I wonder what this does?
#xrdb "${XDG_CONFIG_HOME:-$HOME/.config}/X11/xresources" &  # Personalization
xcompmgr             &  # Transparency
dunst                &  # Desktop notifications
unclutter            &  # Hide mouse when idle
