version: 2

updates:
  - package-ecosystem: "docker"
    commit-message:
      prefix: "build"
      include: "scope"
    directories:
      - "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
  - package-ecosystem: "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    groups:
      all-actions:
        patterns: [ "*" ]
