mode: ContinuousDeployment
continuous-delivery-fallback-tag: mac-os
major-version-bump-message: '(\(breaking|major\))'
minor-version-bump-message: '(\(docs|feature|minor\))'
patch-version-bump-message: '(\(chore|fix|maint|patch\))'
no-bump-message: '\+semver:\s?(none|skip)'
legacy-semver-padding: 3
build-metadata-padding: 3
commits-since-version-source-padding: 3
tag-pre-release-weight: 60000
commit-message-incrementing: Enabled
branches:
  mac-os:
    mode: ContinuousDeployment
    tag: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    regex: ^mac-os$
    source-branches: []
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: true
    pre-release-weight: 0
ignore:
  sha: []
commit-date-format: dd-MM-yyyy
merge-message-formats: {}
update-build-number: true
