column_limit: 140
indent_width: 2
use_tab: false
continuation_indent_width: 4
align_args: true
break_after_functioncall_lp: false
break_before_functioncall_rp: false
align_parameter: true
break_after_functiondef_lp: false
break_before_functiondef_rp: false
chop_down_parameter: false
chop_down_table: true
chop_down_kv_table: true
double_quote_to_single_quote: true
spaces_before_call: 0
table_sep: ','
extra_sep_at_table_end: false
column_table_limit: 120
keep_simple_control_block_one_line: true
keep_simple_function_one_line: true
