APPLY_FIXES: all 
DEFAULT_BRANCH: mac-os
DISABLE:
  - COPYPASTE
  - SPELL
DISABLE_LINTERS:
  - BASH_SHELLCHECK
  - PYTHON_BANDIT
FILEIO_REPORTER: false
PYTHON_BANDIT_DISABLE_ERRORS: true
SHOW_ELAPSED_TIME: true
