{
  "repositoryUrl": "https://github.com/vladdoster/dotfiles",
  "plugins":
    [
      '@semantic-release/commit-analyzer',
      "@semantic-release/release-notes-generator",
      "@semantic-release/release-notes-generator",
      [
        "@semantic-release/changelog",
        {
          "changelogFile": "CHANGELOG.md"
        }
      ],
      [
        "@semantic-release/git",
        {
          "assets": ["CHANGELOG.md"]
        }
      ],
      ["@semantic-release/github", { "assets": "pack/*.tgz" }],
      [
        "@semantic-release/git",
        {
          "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}",
        },
      ],
    ],
}
      #  [
        #  "semantic-release-slack-bot",
        #  {
          #  "notifyOnSuccess": false,
          #  "notifyOnFail": false,
          #  "slackToken": "token",
          #  "slackChannel": "my-channel-name",
          #  "branchesConfig":
            #  [
              #  { "pattern": "lts/*", "notifyOnFail": true },
              #  {
                #  "pattern": "master1",
                #  "notifyOnSuccess": true,
                #  "notifyOnFail": true,
              #  },
            #  ],
        #  },
      #  ],
