cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "wez/wezterm"

brew "autoconf"
brew "automake"
brew "awk", link: true
brew "binutils"
brew "bison"
brew "cmake"
brew "coreutils"
brew "curl"
brew "gcc"
brew "git"
brew "gnu-indent"
brew "gnu-sed"
brew "gnu-tar"
brew "gnu-which"
brew "go"
brew "grep"
brew "gzip"
brew "htop"
brew "less"
brew "lua"
brew "luarocks"
brew "m4"
brew "make"
brew "ncurses"
brew "node"
brew "npm"
brew "stow"
brew "subversion"
brew "tmux"
brew "unzip"
brew "watch"
brew "wget"
brew "xz"
brew "zsh"

# Install GUI applications
cask "1password"
cask "docker"
cask "font-blex-mono-nerd-font"
cask "hammerspoon"
cask "monitorcontrol"
cask "the-unarchiver"
cask "transmission"
cask "vivaldi"
cask "vlc"
cask "wezterm"

# QuickLook plugins
cask "qlcolorcode"
cask "qlmarkdown"
cask "qlstephen"
cask "webpquicklook"

