# CFG
cask_args appdir: "/Applications"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
# CLI
brew "autoconf"
brew "automake"
brew "awk"
brew "binutils"
brew "bison"
brew "brotli"
brew "cmake"
brew "coreutils"
brew "cpanminus"
brew "gcc"
brew "gdbm"
brew "gettext"
brew "git", link: true
brew "git-svn"
brew "gnu-indent"
brew "gnu-sed"
brew "gnu-tar"
brew "gnu-which"
brew "go"
brew "grep"
brew "gzip"
brew "jq"
brew "lua"
brew "luarocks"
brew "m4"
brew "make"
brew "node@16", link: true
brew "subversion"
brew "texinfo"
brew "tmux", link: true
brew "unzip"
brew "watch"
brew "wget"
brew "zsh", link: true
# GUI
cask "1password"
cask "font-blex-mono-nerd-font"
