#!/usr/bin/env zsh
CODE_DIR="${HOME}/code"
if [[ -e $CODE_DIR ]] && [[ -d "$CODE_DIR" ]]; then
    alias c="cd $CODE_DIR"
else
    mkdir "$CODE_DIR"
    alias c="cd $CODE_DIR"
fi

# system specific
if [[ "$OSTYPE" =~ "darwin" ]]; then
    alias ll="gls"
    alias ls='gls -AlhF --color=auto'
    alias readlink="greadlink"
    alias get_public_ssh_key="cat ${HOME}/.ssh/id_rsa.pub | pbcopy -pboard general && echo 'Copied SSH key to clipboard.'"

else
    alias ll="ls"
    alias ls="ls -AlhF --color=auto"
    alias get_public_ssh_key="clip $HOME/.ssh/id_rsa.pub && echo 'Copied SSH key to clipboard.'"
fi

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
# file locations 
alias cpv="rsync -ah --info=progress2"
alias lt="du -sh * | sort -h"
alias mkdir="mkdir -pv"
alias tailf="less +F -R"
# editor
alias get_scratchpad="vim $(mktemp -t scratch.XXX.md)"
alias v.="nvim ."
alias v="nvim"
alias vi="nvim"
alias vim="nvim"

alias edit-aliases="vim $HOME/.zshrc.d/aliases"
alias edit-cli-commands="vim $HOME/.zshrc.d/cli-commands"
alias edit-fzf-commands="vim $HOME/.zshrc.d/fzf-commands"
alias edit-vimrc="vim $HOME/.config/nvim/init.vim"
alias edit-zshrc="vim $HOME/.zshrc"
# git aliases are in ~/.gitconfig.
alias g='git'
# misc.
alias generate_passwd="openssl rand -base64 24"
alias get_my_ip="curl ifconfig.co"
alias reload_zsh="source ${HOME}/.zshrc"
alias reload_bash="source ${HOME}/.bashrc"
# python
alias start_http_server="python -m SimpleHTTPServer"
alias venv_activate="source ./venv/bin/activate"
alias venv_create="python3 -m venv ./venv"
# webserver debugging
alias ping='ping -c 10'                # ping 10 times
alias get_open_ports='netstat -tulanp' # list open ports
alias get_site_headers='curl -I'     # get web server headers
alias headerc='curl -I --compress'     # does remote server supports gzip / mod_deflate
