-- load plugins
require 'plugins'
require 'settings'
require 'misc-utils'
require 'file-tree'
require 'key-bindings'
require 'lsp-completion'
require 'lsp-config'
require 'telescope-config'
require 'treesitter-config'
require 'terminal'
require 'user-interface'
