#!/usr/bin/env zsh

set -Eeuxo pipefail
# Some of these changes still require a logout/restart to take effect.
# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'
# Extract hardware UUID to reconstruct host-dependent plists.
HOST_UUID=$(ioreg -d2 -c IOPlatformExpertDevice | awk -F\" '/IOPlatformUUID/{print $(NF-1)}')
###############################################################################
# Permissions and Access                                                      #
###############################################################################
# CLI to open the automation preference panel:
#   ❯ open "x-apple.systempreferences:com.apple.preference.security?Privacy_Automation"
#
# Raw list of permission names:
#   ❯ strings /System/Library/PrivateFrameworks/TCC.framework/Versions/Current/Resources/tccd | grep "^kTCCService[A-Z a-z]" | sort | uniq
# Ask for the administrator password upfront
sudo -v
# Remove the auto-hiding Dock delay
defaults write com.apple.dock autohide-delay -int 0
defaults write com.apple.dock autohide-time-modifier -int 0
# Automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true
# Disable the sound effects on boot
sudo nvram SystemAudioVolume=" "
# Enable ctrl+option+cmd to drag windows.
# defaults write com.apple.universalaccess NSWindowShouldDragOnGesture -string "YES"
# Enable auto dark mode
defaults write NSGlobalDomain AppleInterfaceStyle -string "Dark"
defaults write NSGlobalDomain AppleInterfaceStyleSwitchesAutomatically -bool true
# Disable the crash reporter
defaults write com.apple.CrashReporter DialogType -string "none"
# Play user interface sound effects
defaults write -globalDomain "com.apple.sound.uiaudio.enabled" -int 0
# Play feedback when volume is changed
defaults write -globalDomain "com.apple.sound.beep.feedback" -int 0
# Do not show password hints
sudo defaults write /Library/Preferences/com.apple.loginwindow RetriesUntilHint -int 0
# Set mouse and scrolling speed.
defaults write NSGlobalDomain com.apple.mouse.scaling -int 3
defaults write NSGlobalDomain com.apple.trackpad.scaling -int 3
defaults write NSGlobalDomain com.apple.scrollwheel.scaling -float 0.6875
# Trackpad: enable tap to click for this user and for the login screen
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults write com.apple.AppleMultitouchTrackpad Clicking -bool true
defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
# Trackpad: right-click by tapping with two fingers
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadCornerSecondaryClick -int 2
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadRightClick -bool true
defaults -currentHost write NSGlobalDomain com.apple.trackpad.trackpadCornerClickBehavior -int 1
defaults -currentHost write NSGlobalDomain com.apple.trackpad.enableSecondaryClick -bool true
# Trackpad: swipe between pages with three fingers
defaults write NSGlobalDomain AppleEnableSwipeNavigateWithScrolls -bool true
defaults -currentHost write NSGlobalDomain com.apple.trackpad.threeFingerHorizSwipeGesture -int 1
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadThreeFingerHorizSwipeGesture -int 1
# Disable “natural” (Lion-style) scrolling
defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false
# Increase sound quality for Bluetooth headphones/headsets.
# Sources:
#     https://www.reddit.com/r/apple/comments/5rfdj6/pro_tip_significantly_improve_bluetooth_audio/
#     https://apple.stackexchange.com/questions/40259/bluetooth-audio-problems-on-a-macbook
for bitpool_param (
  "Negotiated Bitpool"
  "Negotiated Bitpool Max"
  "Negotiated Bitpool Min"
  "Apple Bitpool Max (editable)"
  "Apple Bitpool Min (editable)"
  "Apple Initial Bitpool (editable)"
  "Apple Initial Bitpool Min (editable)"
  ); do
  defaults write com.apple.BluetoothAudioAgent "${bitpool_param}" -int 80
done
# Enable full keyboard access for all controls (e.g. enable Tab in modal dialogs)
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3
# Use scroll gesture with the Ctrl (^) modifier key to zoom
# defaults write com.apple.universalaccess closeViewScrollWheelToggle -bool true
# defaults write com.apple.universalaccess HIDScrollZoomModifierMask -int 262144
# Follow the keyboard focus while zoomed in
# defaults write com.apple.universalaccess closeViewZoomFollowsFocus -bool true
# Disable press-and-hold for keys in favor of key repeat
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool true
# Set a blazingly fast keyboard repeat rate
defaults write NSGlobalDomain KeyRepeat -int 1
defaults write NSGlobalDomain InitialKeyRepeat -int 10
#
# FINDER
#
# Hide all desktop icons (useful when presenting)
defaults write com.apple.finder CreateDesktop -bool false
# Finder: allow quitting via ⌘ + Q; doing so will also hide desktop icons
defaults write com.apple.finder QuitMenuItem -bool true
# Finder: disable window animations and Get Info animations
defaults write com.apple.finder DisableAllAnimations -bool true
# Finder: show hidden files by default
defaults write com.apple.finder AppleShowAllFiles -bool true
# Finder: show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true
# Finder: show status bar
defaults write com.apple.finder ShowStatusBar -bool true
# Finder: show path bar
defaults write com.apple.finder ShowPathbar -bool true
# Display full POSIX path as Finder window title
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true
# Customize toolbar
defaults write com.apple.finder "NSToolbar Configuration Browser" '{ "TB Item Identifiers" = ( "com.apple.finder.BACK", "com.apple.finder.PATH", "com.apple.finder.SWCH", "com.apple.finder.ARNG", "NSToolbarFlexibleSpaceItem", "com.apple.finder.SRCH", "com.apple.finder.ACTN" ); "TB Display Mode" = 2; }'
# Keep folders on top when sorting by name
defaults write com.apple.finder _FXSortFoldersFirst -bool true
# When performing a search, search the current folder by default
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"
# Disable the warning when changing a file extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false
# Enable spring loading for directories
defaults write NSGlobalDomain com.apple.springing.enabled -bool true
# Remove the spring loading delay for directories
defaults write NSGlobalDomain com.apple.springing.delay -float 0
# Avoid creating .DS_Store files on network or USB volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true
# Use list view in all Finder windows by default
# Four-letter codes for the other view modes:
# Icon View   : `icnv`
# List View   : `Nlsv`
# Column View : `clmv`
# Cover Flow  : `Flwv`
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"
# After configuring preferred view style, clear all `.DS_Store` files
# to ensure settings are applied for every directory
# sudo command find / -name ".DS_Store" -print -delete || true
# sudcceo find / -name ".DS_Store" -type f -print -exec sudo rm -f {} \;
/usr/libexec/PlistBuddy \
  -c "Delete :StandardViewOptions:ColumnViewOptions:ColumnShowIcons"    \
  -c "Delete :StandardViewOptions:ColumnViewOptions:FontSize"           \
  -c "Delete :StandardViewOptions:ColumnViewOptions:ShowPreview"        \
  -c "Delete :StandardViewOptions:ColumnViewOptions:ShowIconThumbnails" \
  -c "Delete :StandardViewOptions:ColumnViewOptions:ArrangeBy"          \
  ~/Library/Preferences/com.apple.finder.plist || true
/usr/libexec/PlistBuddy \
  -c "Add :StandardViewOptions:ColumnViewOptions:ColumnShowIcons    bool    true" \
  -c "Add :StandardViewOptions:ColumnViewOptions:FontSize           integer 11"   \
  -c "Add :StandardViewOptions:ColumnViewOptions:ShowPreview        bool    true" \
  -c "Add :StandardViewOptions:ColumnViewOptions:ShowIconThumbnails bool    true" \
  -c "Add :StandardViewOptions:ColumnViewOptions:ArrangeBy          string  dnam" \
  ~/Library/Preferences/com.apple.finder.plist
# Disable the warning before emptying the Trash
defaults write com.apple.finder WarnOnEmptyTrash -bool false
# Enable AirDrop over Ethernet and on unsupported Macs running Lion
defaults write com.apple.NetworkBrowser BrowseAllInterfaces -bool true

# vim: set expandtab filetype=zsh shiftwidth=2 softtabstop=2 tabstop=2:
