#!/usr/bin/env zsh

while [ true ]; do
  echo '================'
  echo total files: $(wc -l <<< "$(ls)")
  echo '================'
  sleep 1
  for i in {1..3}; tput cuu1 && tput el
done

# vim: set expandtab filetype=zsh shiftwidth=2 softtabstop=2 tabstop=2:
