#!/usr/bin/env zsh

autoload -Uz compinit && compinit

if source <(${1} completion -s zsh); then
  compdef _${1} ${1}
  log::info "$1 completion loaded"
  return 0
fi

if source <(${1} completion zsh); then
  compdef _${1} ${1}
  log::info "$1 completion loaded"
  return 0
fi

log::error "Unable to generate $1 completion"
return 1
