#! /usr/bin/env zsh
#
# Author: Vladislav D.
# GitHub: vladdoster
#   Repo: https://dotfiles.vdoster.com
#
# Open an issue in https://github.com/vladdoster/dotfiles if
# you find a bug, have a feature request, or a question.
#
# sources various parts of zsh configuration
#
module_path+=( "/Users/anonymous/.local/share/zsh/zinit/module/Src" )
zmodload zdharma_continuum/zinit
zsh_config=(zinit aliases fzf)
for FILE in ${zsh_config[@]}; do
    . "${ZDOTDIR:-$HOME/.config/zsh}/${FILE}.zsh"
done
