#!/usr/bin/env zsh
CODE_DIR="${HOME:-~}"/code
if [[ ! -e $CODE_DIR ]] || [[ ! -d "$CODE_DIR" ]]; then
    mkdir "$CODE_DIR"
fi
alias c="cd $CODE_DIR"
# system specific
if [[ "$OSTYPE" =~ "darwin" ]]; then
    alias ll="gls"
    alias ls='gls -AlhF --color=auto'
    alias readlink="greadlink"
    alias get-public-ssh-key="cat $HOME/.ssh/id_rsa.pub | pbcopy -pboard general && echo 'Copied SSH key to clipboard.'"
else
    alias ll="ls"
    alias ls="ls -AlhF --color=auto"
    alias get-public-ssh-key="clip $HOME/.ssh/id_rsa.pub && echo 'Copied SSH key to clipboard.'"
fi

echo "$(git rev-parse --show-toplevel "$(readlink -f "$PWD")")"

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
# file locations 
alias cpv="rsync -ah --info=progress2"
alias lt="du -sh * | sort -h"
alias mkdir="mkdir -pv"
alias tailf="less +F -R"
# editor
alias get-scratchpad="vim $(mktemp -t scratch.XXX.md)"
alias v.="nvim ."
alias v="nvim"
alias vi="nvim"
alias vim="nvim"
# config shortcuts
alias e-aliases="vim $ZDOTDIR/.zshrc.d/aliases"
alias e-cli-commands="vim $ZDOTDIR/.zshrc.d/cli-commands"
alias e-dfiles="cd $XDG_CONFIG_HOME/dotfiles && ls"
alias e-fzf-commands="vim $ZDOTDIR/.zshrc.d/fzf-commands"
alias e-tmux="vim $ZDOTDIR/.zshrc.d/fzf-commands"
alias e-vimrc="vim $XDG_CONFIG_HOME/nvim/init.vim"
alias e-zshrc="vim $ZDOTDIR/.zshrc"
alias ez-black="find . -type f -name '*.py' -print -exec python3 -m black --line-length=120 --target-version py38 {} \;"
alias ez-shellharden="find . -type f -name '*.sh' -print -exec shellharden --replace {} \;"
alias ez-shfmt="find . -type f -name '*.sh' -print -exec shfmt -i 4 -s -ln bash -sr -bn -ci -w {} \;"
# git aliases are in ~/.gitconfig.
alias g='git'
# misc.
alias generate-passwd="openssl rand -base64 24"
alias get-my-ip="curl ifconfig.co"
if [[ "$SHELL" =~ "zsh" ]]; then
	alias s-zsh="source $HOME/.zshenv && source $ZDOTDIR/.zshrc"
elif [[ "$SHELL" =~ "bash" ]]; then
	alias s-bash="source $HOME/.bashrc"
fi
# python
alias start-http_server="python -m SimpleHTTPServer"
alias venv-activate="source ./venv/bin/activate"
alias venv-create="python3 -m venv ./venv"
# webserver debugging
alias ping='ping -c 10'                # ping 10 times
alias get-open-ports='netstat -tulanp' # list open ports
alias get-site-headers='curl -I'     # get web server headers
alias headerc='curl -I --compress'     # does remote server supports gzip / mod_deflate
#alias get-kubes-token="kubectl -n kubernetes-dashboard get secret $(kubectl -n kubernetes-dashboard get sa/admin-user -o jsonpath='{.secrets[0].name}') -o go-template='{{.data.token | base64decode}}'"
