#!/usr/bin/env zsh
#--------------------------------------------------
# fd - cd into the directory of the selected file
#--------------------------------------------------
# fd - cd to selected directory
fd() {
  local dir
  dir=$(find "${1:-.}" -path '*/\.*' -prune \
                  -o -type d -print 2> /dev/null | fzf +m) &&
  cd "$dir"
}
#---------------------
# fh - repeat history
#---------------------
fh() {
	eval "$( ([ -n "$ZSH_NAME" ] && fc -l 1 || history) | fzf +s --tac | sed -E 's/ *[0-9]*\*? *//' | sed -E 's/\\/\\\\/g')"
}
#-------------------------------
# fhe - repeat history and edit
#-------------------------------
fhe() {
	print -z "$( ([ -n "$ZSH_NAME" ] && fc -l 1 || history) | fzf +s --tac | sed -E 's/ *[0-9]*\*? *//' | sed -E 's/\\/\\\\/g')"
}
#-----------------------------------------------------
# fkill - kill processes you have permissions to kill
#-----------------------------------------------------
fkill() {
	local pid
	if [ "$UID" != "0" ]; then
		pid=$(ps -f -u "$UID" | sed 1d | fzf -m | awk '{print $2}')
	else
		pid=$(ps -ef | sed 1d | fzf -m | awk '{print $2}')
	fi

	if [ "x$pid" != "x" ]; then
		echo "$pid" | xargs kill -"${1:-9}"
	fi
}
#-----------------------------------------
# fo - open files in finder or editor
# - CTRL-O to open with `open` command,
# - CTRL-E/Enter to open with the $EDITOR
#-----------------------------------------
fo() {
	IFS=$'\n' out=("$(fzf-tmux --query="$1" --exit-0 --expect=ctrl-o,ctrl-e)")
	key=$(head -1 <<<"$out")
	file=$(head -2 <<<"$out" | tail -1)
	if [ -n "$file" ]; then
		[[ "$key" == "ctrl-o" ]] && open "$file" || "${EDITOR:-vim}" "$file"
	fi
}
#-----------------------------------------------------------
# fssh - ssh into a host specified in ~/.ssh/config          
# Takes an argument which will instead execute that command 
#-----------------------------------------------------------
fssh() {
	local command="${1}"
	local host
	host=$(grep '^host .*' ~/.ssh/config | cut -d ' ' -f 2 | fzf)

	[ -z "$host" ] && return

	echo "Connecting to $host"
	[ -n "$command" ] && echo "Command: $command"

	ssh -t "$host" "$command"
}

# Interactive search.
# Usage: `ff` or `ff <folder>`.
ff(){
[[ -n $1 ]] && cd "$1" # go to provided folder or noop
RG_DEFAULT_COMMAND="rg -i -l --hidden --no-ignore-vcs"

selected=$(
FZF_DEFAULT_COMMAND="rg --files" fzf \
  -m \
  -e \
  --ansi \
  --phony \
  --reverse \
  --bind "ctrl-a:select-all" \
  --bind "f12:execute-silent:(subl -b {})" \
  --bind "change:reload:$RG_DEFAULT_COMMAND {q} || true" \
  --preview "rg -i --pretty --context 2 {q} {}" | cut -d":" -f1,2
)

[[ -n $selected ]] && subl "$selected" # open multiple files in editor
}
