#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config \
  active_window_border_color 0xffff0000 \
  active_window_opacity 1.0 \
  auto_balance off \
  bottom_padding 12 \
  focus_follows_mouse off \
  insert_feedback_color 0xffd75f5f \
  layout bsp \
  left_padding 12 \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap \
  mouse_follows_focus off \
  mouse_modifier fn \
  normal_window_border_color 0xff555555 \
  normal_window_opacity 0.90 \
  right_padding 12 \
  split_ratio 0.50 \
  split_type auto \
  top_padding 12 \
  window_animation_duration 0.0 \
  window_border off \
  window_border_blur off \
  window_border_hidpi on \
  window_border_radius 1 \
  window_border_width 4 \
  window_gap 06 \
  window_opacity off \
  window_opacity_duration 0.0 \
  window_origin_display default \
  window_placement second_child \
  window_shadow on \
  window_topmost off \

echo "yabai configuration loaded.."
