name: shfmt

on: push

jobs:
  shellcheck:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
         ref: ${{ github.head_ref }}
    
    - name: Run shfmt linting
      run: |
            docker run --volume "$PWD":/mnt \
                       --rm \
                       mvdan/shfmt -bn -ci -i 4 -p -s -sr -w /mnt
                       
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply shfmt linting changes
        commit_options: '--cleanup=default --no-verify --signoff'
        skip_dirty_check: false  
