name: Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - uses: actions/setup-python@v4
      - uses: actions/setup-go@v3

      - name: install dependencies
        run: |
          sudo apt-get install --yes zsh
          pip install --user linkify-it-py mdformat mdformat-config mdformat-gfm mdformat-shfmt mdformat-tables mdformat-toc
          go install mvdan.cc/sh/v3/cmd/shfmt@latest

      - name: commit
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: '.commitlintrc'
        # run: commitlint --from=$(git cherry origin/main | head -n 1 | awk '{print $2}')

      - name: markdown
        run: find . -name '*.md' ! -name 'CHANGELOG.md' -name '*.md' -type f -print0 | xargs -0 -n1 -P4 mdformat --check --wrap 120

      - name: shell (shfmt)
        run: find . -name '*.sh' -type f -print0 | xargs -0 -n1 -P4 shfmt -bn -ci -d -i 2 -ln bash -s -sr
