name: CI

on:
  push:
    branches: [ mac-os ]
  pull_request:
    branches: [ mac-os ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      GitAssemblyInformationalVersion: ${{ steps.gitversion.outputs.GitAssemblyInformationalVersion }}
      GitBuildVersion: ${{ steps.gitversion.outputs.GitBuildVersion }}
      GitBuildVersionSimple: ${{ steps.gitversion.outputs.GitBuildVersionSimple }}

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: gitversion
      id: gitversion
      run: |
        dir env:
        
        echo "::set-output name=GitAssemblyInformationalVersion::$($env:GitAssemblyInformationalVersion)"
        echo "::set-output name=GitBuildVersion::$($env:GitBuildVersion)"
        echo "::set-output name=GitBuildVersionSimple::$($env:GitBuildVersionSimple)"

  update_release_draft:
    name: Update release draft
    runs-on: ubuntu-latest
    needs: [build]
    env:
      GitAssemblyInformationalVersion: ${{ needs.build.outputs.GitAssemblyInformationalVersion }}
      GitBuildVersion: ${{ needs.build.outputs.GitBuildVersion }}
      GitBuildVersionSimple: ${{ needs.build.outputs.GitBuildVersionSimple }}

    if: github.ref == 'refs/heads/mac-os' # Running this job only for master branch
    steps:

      - uses: release-drafter/release-drafter@v5
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: ${{ needs.build.outputs.GitBuildVersionSimple }}
