---
name: Mega-Linter

on:
  push:
    branches: [mac-os]

env: 
  APPLY_FIXES: all 
  APPLY_FIXES_EVENT: all
  APPLY_FIXES_MODE: commit

jobs:

  cancel_duplicates:
    name: Cancel duplicate jobs
    runs-on: ubuntu-latest
    steps:
      - uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}

  build:

    name: Mega-Linter
    runs-on: ubuntu-latest

    steps:

      - name: checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: run linter
        id: ml
        uses: nvuillam/mega-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/mac-os' }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: prepare commit
        if: steps.ml.outputs.has_updated_sources == 1 
        run: sudo chown -Rc $UID .git/ && ls -al && sudo rm -rf *report* 
          
      - name: Get last commit message
        id: last-commit-message
        run: |
          echo "::set-output name=msg::$(git log -1 --pretty=%s)"

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "(format): apply linter fixes"
          commit_options: '--amend --no-edit --signoff --allow-empty'
          add_options: '-u'
          commit_user_email: mvdoster@gmail.com
          commit_user_name: vladdoster
          push_options: '--force'
          skip_fetch: true
