---
name: Mega-Linter

on:
  push:
    branches: [mac-os]

env: 
  APPLY_FIXES: all 
  APPLY_FIXES_EVENT: all
  APPLY_FIXES_MODE: commit

jobs:

  cancel_duplicates:
    name: Cancel duplicate jobs
    runs-on: ubuntu-latest
    steps:
      - uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}

  build:

    name: Mega-Linter
    runs-on: ubuntu-latest

    steps:

      - name: checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: run linter
        id: ml
        uses: nvuillam/mega-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/mac-os' }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: prepare commit
        if: steps.ml.outputs.has_updated_sources == 1 
        run: sudo chown -Rc $UID .git/ && ls -al && sudo rm -rf *report* 

      - name: commit & push linter fixes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
          commit_message: "(format): apply linter fixes"
