name: Release

"on":
  push:
    branches:
      - master
      - next
      - beta
      - "*.x"
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 16
      - run: npm install --global --no-lock semantic-release/commit-analyzer @semantic-release/changelog @semantic-release/release-notes-generator @semantic-release/github
      - run: npx semantic-release --ci --dry-run --
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
