name: "macOS: release"

on:
  push:
    branches: [mac-os]
  pull_request:
    branches: [mac-os]

jobs:
  
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 1

  linting:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run shfmt linter
        run: |
          docker run --volume "$PWD":/mnt \
                     --rm \
                     mvdan/shfmt -bn -ci -i 4 -ln=bash -s -sr -w /mnt

      - name: Commit shfmt fixes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: (linting) apply shfmt fixes
          commit_options: "--cleanup=default --no-verify --signoff"
          skip_dirty_check: false
          
  build:
    name: Test
    needs: linting
    runs-on: macos-11.0
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          brew install nvim --HEAD
          brew install tmux --HEAD
          brew install stow

      - name: Install dotfiles
        run: |
          make install

  release:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get dependencies
        run: |
          npm install -D release-it \
                         @release-it/bumper \
                         @release-it/conventional-changelog
                
      - name: Create release
        uses: TheRealWaldo/release-it@v0.2.6
            
