name: Release

on:
  workflow_dispatch:

jobs:
  commit:
    uses: vladdoster/.github/.github/workflows/commit.yml@master
  lint:
    needs: [commit]
    uses: vladdoster/.github/.github/workflows/lint.yml@master
  release:
    needs: [lint]
    uses: vladdoster/.github/.github/workflows/release.yml@master
