name: Release Drafter
    
on:                           

  workflow_run:
    workflows: ["format"]
    branches: [master]
    types: 
      - completed
      - requested     

  push:
    branches:
      - master

  pull_request:
    types: [opened, reopened, synchronize]

  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:

  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:

      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set git configuration
        run: |
          git config --global github.user "vladdoster"
          git config --global user.email mvdoster@gmail.com
          git config --global user.name "Vladislav Doster"
          git config --global user.username "vladdoster"

      - name: update_release_draft
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Skip release
        run: |
          echo "[INFO] Skipped release due to earlier failures"
