name: "macOS: devel build"

on:
  push:
    branches: [mac-os]
  pull_request:
    branches: [mac-os]

jobs:

  linting:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run shfmt linter
        run: |
          docker run --volume "$PWD":/mnt \
                     --rm \
                     mvdan/shfmt -bn -ci -i 4 -ln=bash -s -sr -w /mnt

      - name: Commit shfmt fixes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: (linting) apply shfmt fixes
          commit_options: "--cleanup=default --no-verify --signoff"
          skip_dirty_check: false
          
  build:
    name: Test
    needs: linting
    runs-on: macos-11.0
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          brew install stow \
                       nvim \
                       tmux

      - name: Install dotfiles
        run: |
          make dotfiles
         
  pre-release:
    name: Pre-Release
    needs: build
    runs-on: "ubuntu-latest"
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch all history for all tags and branches
        run: |
          git fetch --prune --unshallow
    
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.6.6'
          includePrerelease: false

      - name: Determine Version
        id:   gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7

      - name: "Publish new release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v${{ steps.gitversion.outputs.SemVer }}"
          prerelease: false
          title: "v${{ steps.gitversion.outputs.SemVer }}"
            
