name: Release

on:
  workflow_dispatch:

jobs:
  standards:
    uses: ./.github/workflows/standards.yml
  release:
    needs: [standards]
    uses: vladdoster/.github/.github/workflows/release.yml@master
    secrets:
       github-token: ${{ secrets.GITHUB_TOKEN }}
  container-image:
    needs: [release]
    uses: vladdoster/.github/.github/workflows/containers.yml@master
    secrets:
       github-token: ${{ secrets.GITHUB_TOKEN }}
