name: Release

"on":
  push:
    branches:
      - master
      - next
      - beta
      - "*.x"
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: |
          npm install --no-package-lock \
            @google/semantic-release-replace-plugin \
            @semantic-release/changelog \
            @semantic-release/git \
            semantic-release-slack-bot
      - run: npx semantic-release --ci --dry-run --
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
