name: "release"
    
on:
  workflow_run:
    workflows: ["format"]
    branches: [mac-os]
    types: 
      - completed
      - requested

jobs:

  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
     
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Resolve dependencies
        run: |
           npm install --global release-it \
                                @release-it/bumper \
                                @release-it/conventional-changelog

      - name: Set git configuration
        run: |
          git config --global github.user "vladdoster"
          git config --global user.email mvdoster@gmail.com
          git config --global user.name "Vladislav Doster"
          git config --global user.username "vladdoster"
                
      - name: Publish release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
        run: |
          release-it \
                     --ci \
                     --config=.github/release-it.json \
                     --git.tag=true \
                     --github.preRelease \
                     --preRelease

  on-failure:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Skip release
        run: |
          echo "Skipping release due to formatting workflow failure"
