name: Release
on:
  workflow_dispatch:
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: '**/.github/workflows/release.yml'          
          check-latest: true
      - run: |
          npm install --no-package-lock \
            @google/semantic-release-replace-plugin \
            @semantic-release/changelog \
            @semantic-release/git \
            conventional-changelog-eslint
      - run: npx semantic-release --ci --
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
