name: Release Drafter
    
on:


  pull_request:
    types: [opened, reopened, synchronize]

jobs:

  on-success:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set git configuration
        run: |
          git config --global github.user "vladdoster"
          git config --global user.email mvdoster@gmail.com
          git config --global user.name "Vladislav Doster"
          git config --global user.username "vladdoster"

      - name: update_release_draft
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
