name: Release

on:
  workflow_dispatch:

jobs:
  commit:
    uses: vladdoster/.github/.github/workflows/commit.yml@master
  lint:
    uses: vladdoster/.github/.github/workflows/lint.yml@master
  release:
    uses: vladdoster/.github/.github/workflows/release.yml@master
    secrets:
       github-token: ${{ secrets.GITHUB_TOKEN }}
