name: Arch Linux CI

on:
  push:
    branches: [ arch-linux ]
  pull_request:
    branches: [ arch-linux ]

jobs:

  build:

    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
    - uses: actions/checkout@v2
    - name: update system
      run: pacman -Syyu --noconfirm
    - name: install yay
      run: |
           pacman -S --needed --noconfirm sudo git
           useradd builduser -m
           passwd -d builduser
           printf 'builduser ALL=(ALL) ALL\n' | tee -a /etc/sudoers
           su - builduser bash -c 'cd ~ && \
                                    git clone https://aur.archlinux.org/yay.git yay && \
                                    cd yay && \
                                    makepkg -s --noconfirm'
    - name: install dependencies
      run: |
        whoami
        su - nobody
        whoami
        yay -S --noconfirm \
                         stow \
                         nvim \
                         tmux \
                         make
    - name: install dotfiles
      run: make dotfiles
