name: Arch Linux CI 

on:
  push:
    branches: [ arch-linux ]
  pull_request:
    branches: [ arch-linux ]

jobs:

  build:

    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
    - uses: actions/checkout@v2
    - name: update system
      run: |
            pacman -Syyu --noconfirm
    - name: create non-root user
      run: |
            pacman --sync --needed --noconfirm base-devel git sudo
            useradd test_user -m
            passwd -d test_user
            printf 'test_user ALL=(ALL) ALL\n' | tee -a /etc/sudoers
    - name: install yay
      run: |
            su - test_user bash -c 'cd /tmp && \
                                    git clone https://aur.archlinux.org/yay.git yay && \
                                    cd yay && \
                                    makepkg -si --noconfirm'
    - name: install dependencies
      run: |
        su - test_user bash -c 'yay -S --noconfirm \
                                              stow \
                                              neovim \
                                              tmux \
                                              make'
    - name: install dotfiles
      run: make dotfiles
