name: Arch Linux CI

on:
  push:
    branches: [ arch-linux ]
  pull_request:
    branches: [ arch-linux ]

jobs:

  build:

    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
    - uses: actions/checkout@v2
    - name: create non-root user
      run: |
        useradd --create-home \
                --no-log-init \
                --user-group \
                test
        groupadd -r mygrp && useradd --create-home -r -g mygrp myuser
    - name: update system
      run: pacman -Syyu --noconfirm
    - name: install yay
      run: |
        if ! builtin type -p 'yay' >/dev/null 2>&1; then
            echo 'Install yay.'
            sudo pacman -S --needed base base-devel wget
            tmpdir="$(command mktemp -d)"
            command cd "${tmpdir}" || return 1
            dl_url="$(
                command curl -sfLS 'https://api.github.com/repos/Jguer/yay/releases/latest' |
                command grep 'browser_download_url' |
                command cut -d '"' -f 4
            )"
            command wget "${dl_url}"
            command tar xzvf yay_*_x86_64.tar.gz
            command cd yay_*_x86_64 || return 1
            ./yay -Sy yay-bin
            rm -rf "${tmpdir}"
        fi
    - name: install dependencies
      run: |
        su - test
        yay -S --noconfirm \
                         stow \
                         nvim \
                         tmux \
                         make
    - name: install dotfiles
      run: make dotfiles
