name: Arch Linux CI

on:
  push:
    branches: [ arch-linux ]
  pull_request:
    branches: [ arch-linux ]

jobs:

  build:

    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
    - uses: actions/checkout@v2
    - name: create non-root user
      run: |
        useradd --create-home \
                --no-log-init \
                --user-group \
                --shell /bin/bash \
                test
        groupadd -r mygrp && useradd --create-home -r -g mygrp myuser
    - name: update system
      run: pacman -Syyu --noconfirm
    - name: install yay
      run: |
           whoami
           su - myuser
           pacman -S --noconfirm git
           cd /tmp
           git clone https://aur.archlinux.org/yay.git
           cd yay
           whoami
           makepkg -si
    - name: install dependencies
      run: |
        su - test
        yay -S --noconfirm \
                         stow \
                         nvim \
                         tmux \
                         make
    - name: install dotfiles
      run: make dotfiles
