name: Arch Linux CI

on:
  push:
    branches: [ arch-linux ]
  pull_request:
    branches: [ arch-linux ]

jobs:

  build:

    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
    - uses: actions/checkout@v2
    - name: install yay
      run: |
           cd /tmp
           git clone https://aur.archlinux.org/yay.git
           cd yay
           makepkg -si
    - name: install dependencies
      run: yay -S --noconfirm \
                         stow \
                         nvim \
                         tmux \
                         make
    - name: install dotfiles
      run: make dotfiles
