name: Standards

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  commit:
    name: Check
    uses: vladdoster/.github/.github/workflows/commit.yml@master
  lint:
    name: Check
    uses: vladdoster/.github/.github/workflows/lint.yml@master
