name: Bump version

on:
  workflow_dispatch:

jobs:
  bump_version:
    runs-on: ubuntu-latest
    name: 'Bump version and create changelog with commitizen'
    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: true
    - name: Set git configuration
      run: |
        git config --global github.user "vladdoster"
        git config --global user.email mvdoster@gmail.com
        git config --global user.name "Vladislav Doster"
        git config --global user.username "vladdoster"
    - name: Create bump and changelog
      uses: commitizen-tools/commitizen-action@master
      with:
        github_token: ${{ secrets.GH_ACTIONS_TOKEN }}
        changelog_increment_filename: "VERSION"
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: "VERSION"
        tag_name: ${{ env.REVISION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
